apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secrets
  namespace: default
spec:
  encryptedData:
    DB_PWD: AgCxHhqcqhkg1DWKvG0Ipf4AiDHp+tCVyJ2v+GUzlob3zEStMZMTmVuwz6VSN/Ss+WcQ/wJlDtP4c7s+I6YvoJXgR4s9t+pbEA2NjC7vpvpAXMS27mguByW40spR2OWYgSfbr49mx6KgRjZ1SCx0kvgz1bIId09MXyCYBNMVj9pqJX77F9siW43Zo23bl9CyqNXfLZh9vo/uEjyKU0Nx67Ms+D2ZFV3u7syWNVyVaHCrofDnJ871z6aNvNnqP+A3QMrsNBFVSbdRq/LSv7vQIuRKo7zLuX113WXSP406VadOtM/my6rVT3RLmxL75TPKEfTQ4IE0jy55+qyJN0YoRCvTIyBDaSAdDCaZlO6eVhFf/eGVqMBBW5cTye/9I5WfouB9Ble4o0/fjwth9dahZ82P+xDxRlLzKhM4zXPmkoc1vHHrlsdypItHxbMnLQWBxOY4GSi87xiW5pj5DeMb2MYlcCnZ9ZDt+Qd4D0BSZxQFI5X192r4IE1THbHOc8vtHTDWhMQ7OEQyz+ow02CoH0hmThc8iji7/LCrKXn1rAdVojLx6o+u/ixR6tNeQQmmgM1i9XgplVKQL10B4uRJmRW8NlieZw5Q1Q1ZeHSyPRMKiNR9UNxkvbNHuX0fZKO46Ee5TJOdYMOyeQRgoiffqUHs7RMZXdaD0sKu+Qr7EdugWAJyewtphnhKweKFFgUaLpUmyN5bNkH0mM1IkL0r
    DB_USER: AgBoEgS0iLY5Tmng+nMxyZGa0clBEupaNKjYkx92gY7OT7zaIQFdlUMhSKMrYC1qyv8l6l9qRWBI+i9ZA0ZNx2FCca78WHRrNaVtKI42emvhPWNUy8I1Fw6RKXBFvOVlDR2/xAG0MT0eikjKngz1Y+5L1h/Mj/+MVtO3u3riNlMbAzD1//3/U9VexF5AWEsHWFFdy5kZcl/LhUSXKR8+DfeBz0oOluI8qCsC9BefA8YYYd55Dbo0kMAKlK3N9V3tjmTPpaHSElVreDiIWVs2bZ4r691QSJfP6r79KT3f+Tq1nZrSSP+zWX7SHTYSTG3CoZjxRfhMgljW4TiRGrKhSpy6kq2zLFiWMxpMdSGzrjJlRNp5Nd8eyt0G1jXV8+5PgxKgxSx0BYOyjLDHVF5r2SocmxDQSjPGuX9uRFmn0405Do8Zr1CEAH3XtUO5vx0wQ9nBjAAtCmQKdIx/zbMC6rHNvqGSNzC83Mj6dHMG9f5u3vI3M1oGhvR/ZUdeEbmC0GtIBwLCeGQ/O59WW9yDP3W9qdEXUu0q5bOg96H9UFFOXvOGLaeFyQ8ZrPg7ierc7JtY8LQrQ4eul57Rh/14SFZ2gpjr+E5hWXW+VCNLPRz8VkrvLYIMVZL1Xf0+cVJIdN5ZFurhzIhrGSql39mbnnqTEQGH5hwRKcqXWChaoLTRgVB1vVA5cr0IRIlPkD8NLyBqst8FntzsRjA0BFKh16PK
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: db-secrets
      namespace: default

