apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secrets
  namespace: default
spec:
  encryptedData:
    DB_PWD: AgA23qZTbVjME4lwejPgK/XbIEE/CUEU1YAhWhn+1Ja844weq0texqWl01aI+ECPxM8029mJzNkn/ev2bWL1D7SkgoOVYcEYPeHdK0jg4o3Ebd69gcsUjxKnIJ/0ibABx2ROXCKdBSpCkdm6BwuUQvunHZp/CGvWxR1v1giqEckxFId6khZiaeUjs7hcri0W0HQ8PEV7MecMqoxgrd/voiaAH0Ny4vocECw7GBs1UgwkKGYLSqL85TNKOhFqSp1r/9FxYvsdk8s9Z+ABvyJ/IvF3pNIRXeVitrzjkHMHrvD0TSckyiUeVNwlgncl/4/nv79TJrHiY8T6tti/uRGLWCZgiAY2069sx8NhFVtFpTtfSNNq/SA5ySfV4oVSMYg1ViZcjEV90GwCI0XongoxICDfUHX57mCuTzwQEozSieRfaaoG0lNmUbBbwbprYRR1NjgDzg9yNVPQ9VDsmQpbc5MpIVYBhR7dNdee2eoB+eNQ/Njzv1B8fJvAiM+3Mqqp3zfyNb7yY4k5egSOJhMl6TbgTQu1YOO3N32tdXU0ub/rOmoyb29x+mhszjsBkEugt7F8diPuOHiEyxu7p869kXgyToWPLpnTzyRZq5NsGeAm4MnnK477W2ktc5NAvjTDgIzJf4DqJFkquLu8XolupxL+1Ubnl+C/RxErp3aeGbgw7D6QBcYii9LN1zahbZQcVdd6onaQU8rOzA2fSY4=
    DB_USER: AgCNqdi+Gh+t9hZh9PDMf6baZvASmCIi3f+t8TPuIENy+3ro8vnDBNFPsHaAtzg91bXujo2n+kZHmr59hnS6ZdsmWbjVqiDbUYbFiBWIAA6WSIT6RZfT7qAqMLf0ABVWr9+Bcyn46V+NQdiQcTdLikredP1DsKcEh6ZNCOlQc8lqU3qLkFamtqiUhnPGNPr2r2YvsZxGV2eWtYHellVqFN3Cn5SAdJL130sHevob8cgMO52vcC5yE5SGRQ9FOx6alxpXxEilIt1I1rsX2j1wbz5L14JPoEUYO2C8FzgBF2EXs06qQ3f9mX7wmnCC6iLWYI0mDzDiPvvrvs8R/SiI1nfGzaanlvqsOZ86Lkppufh0hiBq3ky20Zg4UWi7oH2sjh+JlCE8UAVtmV+ArY/hSFB3mB4Hay+NKFemQaC/xTZMncnDKySt+AD/yqaBUVbe3yWJvWA9rM4wqGEhy2xcj/cqSBd2i0kDu7Bmdj1lcpDWmViu7nKlFuvuvBgwRG/+VEsonLcLbIlCwoIZKL8SH7tbPo7E0HXp4quoBLWa4CgAVnEHK6xDt0APmFNLkGaXRjWGeNXivUJUQqcjGURsszF0aTIlXCh8gP6Aw4gXREcVtXg8S94W4oujsdta4gw+Xd2UmMw47LvqrlJfGeBCi7IDLf2V59KGO9CEzYehDTQd+5ZMJuxLSm+bij63asIVY2Fie+w0jo2SVCVk/I9MjNA=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: db-secrets
      namespace: default

