apiVersion: v1
kind: Service
metadata:
  name: service-node3tier-api
  namespace: default

spec:
  selector:
    app: node3tier-api

  type: NodePort

  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: service-node3tier-web
  namespace: default

spec:
  selector:
    app: node3tier-web

  type: NodePort

  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
